
set(NIND_VERSION "@NIND_VERSION@")

set(NIND_VERSION_MAJOR "@NIND_VERSION_MAJOR@")
set(NIND_VERSION_MINOR "@NIND_VERSION_MINOR@")
set(NIND_VERSION_PATCH "@NIND_VERSION_PATCH@")

set(NIND_LIB_VERSION "@NIND_LIB_VERSION@")
set(NIND_LIB_SOVERSION "@NIND_LIB_SOVERSION@")

